no_empty_title:
  level: disabled # all of the imported linkml types fail this test
permissible_values_format:
  level: disabled # may conflict with the standard_naming rule
tree_root_class:
  level: warning # we are not currently requiring this in m30ml
recommended:
  level: error # if a linkml schema slot is recommended, ensure it is used
no_xsd_int_type:
  level: warning # use xsd:integer in place of xsd:int
no_invalid_slot_usage:
  level: error # ensure all slots in schema def are part of linkml schema
standard_naming:
  level: error # create names consistent with linkml approach
canonical_prefixes:
  level: disabled # most of our prefixes are internal to m30ml and its derivatives